/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  docsSidebar: [
    'overview/introduction', 
    'overview/run-your-first-project',
    {
      type: 'category',
      collapsible: false,
      label: 'Software',
      items: [
        'overview/software/madmachine-ide',
        'overview/software/mm-sdk',
      ],
    },
    {
      type: 'category',
      collapsible: false,
      label: 'Hardware',
      items: [
        'overview/hardware/swiftio-board',
        'overview/hardware/swiftio-feather',
        'overview/hardware/maker-kit',
        'overview/hardware/circuit-playgrounds',
      ],
    },
    'overview/background', 
    'overview/faq', 
  ],

  howToSidebar: [
    'how-to/create-new-project',
    'how-to/open-project',
    'how-to/select-board',
    'how-to/debug',
    'how-to/add-library',
    'how-to/write-library',
  ],

  // learnSidebar: [
  //   'learn/overview',
  // ],

  tutorialSidebar: [
    'tutorials/overview',
    {
      type: 'category',
      collapsed: false,
      label: 'General',
      items: [

        {
          type: 'category',
          collapsed: false,
          label: 'GettingStarted',
          items: [
            'tutorials/general/getting-started/blink',
            'tutorials/general/getting-started/read-digital-input',
            'tutorials/general/getting-started/read-analog-input',
            'tutorials/general/getting-started/pwm-brightness-control',
          ],
        },
        {
          type: 'category',
          collapsed: false,
          label: 'SimpleIO',
          items: [
            'tutorials/general/simpleio/button-control-led',
            'tutorials/general/simpleio/blink-analogin',
            'tutorials/general/simpleio/blink-timer',
            'tutorials/general/simpleio/brightness-analogin',
            'tutorials/general/simpleio/leds-brightness-control',
            'tutorials/general/simpleio/debounce',
            'tutorials/general/simpleio/pwm-sound-output',
            'tutorials/general/simpleio/pwm-melody',
           
          ],
        },


      ],
    },
    {
      type: 'category',
      collapsed: false,
      label: 'SwiftIO Maker Kit',
      items: [
        'tutorials/swiftio-maker-kit/mission1',
        'tutorials/swiftio-maker-kit/mission2',
        'tutorials/swiftio-maker-kit/mission3',
        'tutorials/swiftio-maker-kit/mission4',
        'tutorials/swiftio-maker-kit/mission5',
        'tutorials/swiftio-maker-kit/mission6',
        'tutorials/swiftio-maker-kit/mission7',
        'tutorials/swiftio-maker-kit/mission8',
        'tutorials/swiftio-maker-kit/mission9',
        'tutorials/swiftio-maker-kit/mission10',
        'tutorials/swiftio-maker-kit/mission11',
        'tutorials/swiftio-maker-kit/mission12',
      ],
    },
    {
      type: 'category',
      collapsed: false,
      label: 'SwiftIO Circuit Playgrounds',
      items: [

        {
          type: 'category',
          collapsed: false,
          label: 'Get familiar with modules',
          items: [
            'tutorials/swiftio-circuit-playgrounds/modules/led',
            'tutorials/swiftio-circuit-playgrounds/modules/button',
            'tutorials/swiftio-circuit-playgrounds/modules/led-timer',
            'tutorials/swiftio-circuit-playgrounds/modules/buzzer',
            'tutorials/swiftio-circuit-playgrounds/modules/potentiometer',
            'tutorials/swiftio-circuit-playgrounds/modules/humiture',
            'tutorials/swiftio-circuit-playgrounds/modules/accelerometer',
            'tutorials/swiftio-circuit-playgrounds/modules/lcd',
            'tutorials/swiftio-circuit-playgrounds/modules/speaker',
          ],
        },

        {
          type: 'category',
          collapsed: false,
          label: 'Graphical display',
          items: [
            'tutorials/swiftio-circuit-playgrounds/display/before-start',
            'tutorials/swiftio-circuit-playgrounds/display/maddisplay',
            'tutorials/swiftio-circuit-playgrounds/display/shapes',
            'tutorials/swiftio-circuit-playgrounds/display/text',
            'tutorials/swiftio-circuit-playgrounds/display/bmp',
          ],
        },
        {
          type: 'category',
          collapsed: false,
          label: 'More projects',
          items: [
            'tutorials/swiftio-circuit-playgrounds/projects/overview',
            'tutorials/swiftio-circuit-playgrounds/projects/doorbell',
            'tutorials/swiftio-circuit-playgrounds/projects/movingBall',
            'tutorials/swiftio-circuit-playgrounds/projects/etchASketch',
            'tutorials/swiftio-circuit-playgrounds/projects/metronome',
            'tutorials/swiftio-circuit-playgrounds/projects/morseCode',

          ],
        },

      ],
    },

  ],

  referenceSidebar: [
    'reference/reference',
  ],
};
