/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  docsSidebar: [
    'overview/introduction', 
    'overview/run-your-first-project',
    {
      type: 'category',
      collapsible: false,
      label: 'Software',
      items: [
        'overview/software/madmachine-ide',
      ],
    },
    {
      type: 'category',
      collapsible: false,
      label: 'Hardware',
      items: [
        'overview/hardware/swiftio-board',
        'overview/hardware/swiftio-feather',
      ],
    },
    'overview/faq', 
  ],

  howToSidebar: [
    'how-to/create-new-project',
    'how-to/open-project',
    'how-to/select-board',
    'how-to/debug',
    'how-to/use-mm-sdk',
    'how-to/add-library',
    'how-to/write-library',
  ],

  learnSidebar: [
    'learn/overview',
  ],

  tutorialSidebar: [
    'tutorials/overview',
  ],

  referenceSidebar: [
    'reference/reference',
  ],
};
